FROM golang:1.17.6-alpine AS functional-test
RUN apk add --update docker openrc
RUN rc-update add docker boot
WORKDIR /src
ENV CGO_ENABLED=0
COPY go.mod .
COPY go.sum .
COPY functional_test.go .
RUN go mod tidy
RUN go mod download
