FROM golang:1.17.6-alpine AS base
RUN apk add --update docker openrc
RUN rc-update add docker boot
WORKDIR /src
ENV CGO_ENABLED=0
COPY go.mod .
COPY go.sum .
RUN go mod tidy
RUN go mod download
RUN go get github.com/ory/dockertest/v3
RUN go get -t github.com/fernandovaladao/vwap
COPY functional_test.go .