FROM golang:1.17.6-alpine AS base
WORKDIR /src
ENV CGO_ENABLED=0
COPY go.mod .
COPY go.sum .
RUN go mod download
RUN go install github.com/golang/mock/mockgen@v1.6.0
COPY . .

FROM base AS build
RUN go build -o /bin/vwap .

FROM base AS unit-test
RUN go generate ./...
RUN go test -v ./...

FROM scratch AS bin
COPY --from=build /bin/vwap /
